In [ ]:
#Exo1
import numpy as np

# Creating a 1D array
array = np.arange(0,10)
print(array) 

[0 1 2 3 4 5 6 7 8 9]


In [6]:
#Exo2
import numpy as np

# Convertrir 1D array to int 
array_float = np.array([3.14, 2.17, 0, 1, 2], dtype=int)

# Affichage du tableau et de son type de données
print(array_float)

[3 2 0 1 2]


In [25]:
#Exo3
import numpy as np

# Creating a 1D array
array_3 = np.arange(1, 10)  # Array of numbers from 1 to 9

# Reshaping to a 3x3 matrix
reshaped_array = array_3.reshape(3,3)
print("Reshaped to 3x3:\n", reshaped_array)

Reshaped to 3x3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
#Exo4
#un tableau 4*5 avec des valeurs aléatoires
random_values = np.random.rand(4, 5)

# Affichage du tableau
print("Tableau bidimensionnel (4, 5) avec des valeurs aléatoires :")
print(random_values)

Tableau bidimensionnel (4, 5) avec des valeurs aléatoires :
[[0.36311729 0.11460185 0.02337802 0.66120874 0.62338108]
 [0.1294098  0.80080025 0.50613205 0.51427477 0.2095684 ]
 [0.84076774 0.31247334 0.89221308 0.00821433 0.55561851]
 [0.3726206  0.22905557 0.86756149 0.92266069 0.68690774]]


In [17]:
#Exo5
import numpy as np

# Création d'un tableau NumPy 2D
array_2d = np.array([[21,22,23,22,22], 
                      [20,21,22,23,24], 
                      [21,22,23,22,22]])
print("deuxième ligne :  " , array_2d[1,:])

deuxième ligne :   [20 21 22 23 24]


In [24]:
#Exo6
import numpy as np

# Creating a 1D array
array_4 = np.arange(0, 10) 
#inverser l'ordre des éléments et l'afficher
np.flip(array_4)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [29]:
#Exo7
import numpy as np

# Creating a 1D array
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#Exo8
import numpy as np

# Création d'un tableau 1D
array_sm = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Trouver la somme
somme = np.sum(array_sm)

# Trouver la moyenne
moyenne = np.mean(array_sm)
print("la somme est :",somme)
print("la moyenne est:", moyenne)

la somme est : 55
la moyenne est: 5.5


In [41]:
import numpy as np

# Creating a 1D array
array_resh = np.arange(1,21)  # Array of numbers from 1 to 20

# Reshaping to a 4x5 matrix
reshaped_array = array_resh.reshape(4, 5)
print("Reshaped to 4x5:\n", reshaped_array)

Reshaped to 4x5:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [42]:
# Création d'un tableau 1D d'exemple
array_im = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np.extract(array_im % 2 != 0, array_im)

array([1, 3, 5, 7, 9])