In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Users\DELL 3510\AppData\Local\Programs\Python\Python38\python.exe -m pip install --upgrade pip' command.


In [8]:
import numpy as np

# Création d'un tableau NumPy de 1 a 6 2D
array = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([1, 2, 3,4, 5])

# Affichage du tableau
print(array)
print(array2)
print(f"  → Forme  (shape)  : {array.shape}")
print(f"  → Taille (size)   : {array.size}")
print(f"  → Type   (dtype)  : {array.dtype}\n")

array_float = np.array([1, 2, 3], dtype=float)

# Affichage du tableau et de son type de données
print("Tableau :", array_float)
print("Type de données :", array_float.dtype)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5]
  → Forme  (shape)  : (2, 3)
  → Taille (size)   : 6
  → Type   (dtype)  : int32

Tableau : [1. 2. 3.]
Type de données : float64


In [15]:
#EXO2
import numpy as np

# Création d'un tableau NumPy de 1 a 6 2D
temperatures = np.array([24, 29 , 18, 20, 17])

# Affichage du tableau
print("Températures de cette semaine : ", temperatures)
print(f"  → Forme  (shape)  : {temperatures.shape}")
print(f"  → Taille (size)   : {temperatures.size}")
print(f"  → Type   (dtype)  : {temperatures.dtype}\n")


#un tableau 2x5 avec des valeurs aléatoires entre 1 et 10
random_values = np.random.randint(1, 11, size=(2, 5))

# Affichage du tableau
print("Tableau bidimensionnel (2, 5) avec des valeurs aléatoires :")
print(random_values)

# Créer un tableau 3D représentant une image 3x3 avec des valeurs de pixels définies manuellement
# Chaque pixel est représenté par trois valeurs : R, G, B
image_pixels = np.array([[[255, 0, 0], [0, 255, 0], [0, 0, 255]],   # Première ligne de pixels
                        [[255, 255, 0], [0, 255, 255], [255, 0, 255]], # Deuxième ligne de pixels
                        [[192, 192, 192], [128, 128, 128], [0, 0, 0]]]) # Troisième ligne de pixels

# Affichage du tableau
print("Tableau 3D représentant une image de 9 pixels (3x3 avec 3 canaux) :")
print(image_pixels)

Températures de cette semaine :  [24 29 18 20 17]
  → Forme  (shape)  : (5,)
  → Taille (size)   : 5
  → Type   (dtype)  : int32

Tableau bidimensionnel (2, 5) avec des valeurs aléatoires :
[[ 1  1  7  9  7]
 [ 9  4  9 10 10]]
Tableau 3D représentant une image de 9 pixels (3x3 avec 3 canaux) :
[[[255   0   0]
  [  0 255   0]
  [  0   0 255]]

 [[255 255   0]
  [  0 255 255]
  [255   0 255]]

 [[192 192 192]
  [128 128 128]
  [  0   0   0]]]


In [ ]:
#test_cours

import numpy as np

# Example 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing a single element
print("Element at row 1, column 2:", array_2d[1, 2])  # Output: 6
array_2d[1, 2]
#signifie que l'on souhaite accéder à l'élément situé à la ligne 1 et à la colonne 2 du tableau.
#Dans l'exemple ci-dessus, cela correspond au nombre 6 dans le tableau.

# Accessing a row
print("Second row:", array_2d[1, :])  # Output: [4 5 6]
array_2d[:, 2] array_2d[1, :] #signifie que l'on souhaite accéder à la ligne 1 (la deuxième ligne, 
#puisque l'indexation commence à 0) et à toutes les colonnes de cette ligne.
#Le résultat ici sera [4, 5, 6], soit la deuxième ligne du tableau.

# Accessing a column
print("Third column:", array_2d[:, 2])  # Output: [3 6 9]
array_2d[:, 2] 
#signifie que l'on souhaite accéder à la colonne 2 (la troisième colonne) pour toutes les lignes du tableau.
#Le résultat ici sera [3, 6, 9], soit la troisième colonne du tableau.

Element at row 1, column 2: 6
Second row: [4 5 6]
Third column: [3 6 9]


In [17]:
#testcours
import numpy as np

# Example 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slicing a portion of the array
print("Slice of the array:", array_2d[0:2, 1:3])  # Output: [[2 3] [5 6]]

Slice of the array: [[2 3]
 [5 6]]


In [18]:
import numpy as np

# Creating a 1D array
a = np.array([1, 2, 3])

# Adding a scalar value to the array
result = a + 5

print("Original Array:", a)
print("After Adding 5:", result)

Original Array: [1 2 3]
After Adding 5: [6 7 8]


In [20]:

import numpy as np

# Creating a 1D array and a 2D array
a = np.array([0, 1, 2])
b = np.array([[0, 1, 2], [3, 4, 5]])

# Adding the 1D array to each row of the 2D array
result = a + b

print("1D Array:", a)
print("2D Array:", b)
print("Broadcasted Addition:", result)

1D Array: [0 1 2]
2D Array: [[0 1 2]
 [3 4 5]]
Broadcasted Addition: [[0 2 4]
 [3 5 7]]


In [34]:
#cours6
import numpy as np

# Creating a 1D array
array = np.arange(0, 12)  # Array of numbers from 1 to 9

# Reshaping to a 3x3 matrix
reshaped_array = array.reshape(4,3)
print("Reshaped to 4x3:\n", reshaped_array)
# Reshaping to a 3x3 matrix
reshaped_array = array.reshape(2,6)
print("Reshaped to 2x6:\n", reshaped_array)
transposed_array = array
print("\nMatrice transposée (6x2) :")
print(transposed_array)

Reshaped to 4x3:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Reshaped to 2x6:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Matrice transposée (6x2) :
[ 0  1  2  3  4  5  6  7  8  9 10 11]
